<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>tems and conditions account alerts</title>
</head>

<body>
<p><br />
</p>
<p>Terms Of Use Account Alerts</p>
<p>WeFinanceHere.com Account Alerts (the “Service”) enables you to request and receive notices (collectively, “Alerts”, individually, an &quot;Alert&quot;) from time to time concerning available account information and other matters relating to your WeFinanceHere.com(&quot;Approvals&quot;). You may request and receive Alerts through a SMS-enabled mobile device (“Mobile Alert”). You may also choose to receive Alerts at an e-mail account that is accessed via a personal computer (“E-mail Alert”). The Service is provided by WeFinanceHere.com, LLC for WeFinanceHere.com customers. “WFH”, “we”, “us” and “our” mean WeFinanceHere.com, LLC and its successors and assignees. The Service is only available to those over the age of majority in their state who have been issued a valid Driver Licenses and who has means to repay any financial loans and obligations the legal age requirements of the residents state may use this service and agree to the terms of this agreement.  By signing up to receive one or more of the Alerts that are offered by the Service, you acknowledge that you are aware of and agree to abide by the following terms and conditions:</p>
<p>1. Service Terms And Conditions</p>
<p>Please be certain to review terms and conditions specific to Mobile Alerts and E-Mail Alerts, below.</p>
<p>You acknowledge and agree that your receipt of any Alert may be delayed or prevented by factor(s) outside of our control, including factors affecting your wireless service provider and coverage in your area. We do not guarantee the delivery, timeliness or accuracy of the contents of each Alert. The Service is subject to transmission limitations and service interruptions. You agree to indemnify, defend and hold WeFinanceHere.com(the issuer of the Approval ), WeFinanceHere.com and their respective directors, officers, employees and agents (collectively, “Released Parties”) free and harmless from any and all losses or damages, including attorneys' fees, lost profits, and indirect or special damages, including, but not limited to, to those relating to bank secrecy or financial privacy laws or regulations, that may arise, directly or indirectly, in whole or in part, from: a non-delivery, delayed delivery, or the misdirected delivery of an Alert; inaccurate or incomplete content in an Alert; your reliance on or use of the information provided in an Alert for any purpose; or any third party, whether authorized or not, obtaining information regarding your Approval  disclosed in the Alerts.</p>
<p>THE RELEASED PARTIES DISCLAIM ANY RESPONSIBILITY AND ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICE. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND YOU ACKNOWLEDGE USE OF THE SERVICE IS AT YOUR SOLE RISK. THE RELEASED PARTIES DISCLAIM ANY AND ALL LIABILITY FOR THE SERVICE UNDER ANY CAUSE OF ACTION. IF ANY PART OF THESE TERMS AND CONDITIONS ARE FOUND VOID AND UNENFORCEABLE, IT WILL NOT AFFECT THE VALIDITY OF THE REMAINDER, WHICH SHALL REMAIN VALID AND ENFORCEABLE ACCORDING TO THEIR TERMS.</p>
<p>We provide the Service purely as a convenience to you and for information purposes only. Alerts do not constitute a record for the Approval  to which it pertains. We do not assume any additional responsibility or obligation under these terms and conditions in respect of the use of, or any transaction or eventuality involving, your Approval . The Service does not free you from the responsibility of safeguarding the physical security and authorized use of your account and accurate information.</p>
<p>We reserve the right to suspend, terminate, and modify the Service without liability at any time without prior notice to you.</p>
<p>If you use the Service, you agree that we may also send you messages regarding your Approval , including, but not limited to, alerts that your Approval  is about to expire, alerts regarding the status of your Approval , or alerts regarding items requiring your attention with respect to your Approval . Subscription to the Service confirms that you have read, understood and agree to the above terms and conditions, as well as to the terms and conditions in the Approval holder Agreement. These terms and conditions do not supersede or modify the Approval holder Agreement, and if any of its terms are found to conflict with the Approval holder Agreement, then the terms of the Approval holder Agreement will prevail.</p>
<p>We may deactivate the sending of Alerts to you if your Approval  is not used for a purchase, vehicle transaction, or login for a period of sixty (60) days. If Alerts are deactivated for your Approval  and you application use of your Approval  and wish to restore Alerts, you will be required to re-enroll your Approval and verification  in your backoffice account regarding Alerts service to restore Alerts.</p>
<p>2. Mobile Alert Additional Terms And Conditions</p>
<p>The Service allows you to request and receive Mobile Alerts. We send Mobile Alerts to you based upon the instructions you provide to us, including the mobile number you provide to us at WeFinanceHere.com. You hereby acknowledge and accept that each Mobile Alert may be sent to you without being encrypted and may include your name and information pertaining to your Approval . Depending upon which alerts you select, information such as your account balance may be included. Anyone with access to your mobile device will be able to view the contents of these Alerts. For help regarding Mobile Alerts, text “HELP” to 96411 or contact us. You can unsubscribe from Mobile Alerts at any time by texting “STOP” to 96411. By enrolling in Mobile Alerts, you are consenting to receive Mobile Alerts and other messages via text message to your mobile device, including a confirmation receipt of STOP messages. Message and data rates may apply. See your wireless provider for pricing plan details.</p>
<p>It is your responsibility to: ensure the security of your mobile device; determine if your wireless provider supports SMS; and ensure your mobile device is capable of receiving SMS. You acknowledge that message and data rates may apply. You are solely responsible for any fees imposed of any kind whatsoever by your wireless service provider.</p>
<p>The Service is available on these US carriers only: AT&amp;T, Sprint, Nextel, Verizon Wireless, U.S. Cellular, T-Mobile, Cellular One Dobson, Cincinnati Bell, Alltel, Virgin Mobile USA, Cellular South, Unicel, Centennial, Ntelos</p>
<p>3.	E-Mail Alert Additional Terms And Conditions</p>
<p>The Service allows you to receive E-mail Alerts about your Approval . We send E-mail Alerts to you based upon the instructions you provide to us, including the email address you provide us on WeFinanceHere.com. You hereby acknowledge and accept that each E-mail Alert may be sent to you without being encrypted and may include your name and information pertaining to your Approval . Depending upon which alerts you select, information such as your account balance may be included. Anyone with access to your email will be able to view the contents of these Alerts. You may unsubscribe from E-Mail Alerts anytime by managing your Account Alert preferences at WeFinanceHere.com.</p>
<p>It is your responsibility to ensure the security of your e-mail account. You are solely responsible for any fees imposed of any kind whatsoever by your Internet service provider.</p>
<p>Effective October 17, 2016</p>
</body>
</html>